# Forge Pod (Gitea) Docker Compose File
# Includes Gitea and Gitea-Runner
services:
  gitea:
    image: docker.io/gitea/gitea:latest-rootless
    container_name: gitea
    volumes:
      - ./gitea/app.ini:/etc/gitea/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - gitea-data:/var/lib/gitea
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=database:5432
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWD}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2048M"
        reservations:
          cpus: "0.25"
          memory: "1024M"
    networks:
      homelab-net:
        aliases:
          - gitea
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - database

  gitea-runner:
    image: docker.io/gitea/act_runner:latest
    container_name: gitea-runner
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1024M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    networks:
      homelab-net:
        aliases:
          - gitea-runner
    ports:
      - "8086:80"

volumes:
  gitea-data:

networks:
  homelab-net:
    external: true