services:
  nginx-backend:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-backend
    restart: unless-stopped
    volumes:
      - ./nginx-backend/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "64M"
    networks:
      homelab-net:
        aliases:
          - nginx-backend
    ports:
      - "8090:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - backend-data:/app/data/pb_data
      - backend-public-data:/app/data/pb_public
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1024M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    networks:
      homelab-net:
        aliases:
          - backend

volumes:
  backend-data:
  backend-public-data:
  
networks:
  homelab-net:
    external: true