services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - DB_POSTGRESDB_SCHEMA=public
      - TZ=Africa/Windhoek
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"
        reservations:
          cpus: "0.10"
          memory: "64M"
    networks:
      homelab-net:
        aliases:
          - n8n

  # db:
  #   image: postgres:14
  #   container_name: n8n-db
  #   environment:
  #     - POSTGRES_DB=n8n
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8npass
  #   volumes:
  #     - n8n_db_data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  n8n_data:
  n8n_db_data:

networks:
  homelab-net:
    external: true