global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: '${MY_SERVICE_JOBNAME}'
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['${MY_SERVICE_HOST}']
    authorization:
      type: 'Bearer'
      credentials: '${MY_SERVICE_PASSWORD}'