# Database Pod (PostgreSQL) Docker Compose File
# Includes PostgreSQL
services:
  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    volumes:
      - ./postgres/postgres.json:/etc/postgres/postgres.json
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      GITEA_DB_USER: ${GITEA_DB_USER}
      GITEA_DB_PASSWORD: ${GITEA_DB_PASSWORD}
      GITEA_DB_NAME: ${GITEA_DB_NAME}
      WOODPECKER_DB_USER: ${WOODPECKER_DB_USER}
      WOODPECKER_DB_PASSWORD: ${WOODPECKER_DB_PASSWORD}
      WOODPECKER_DB_NAME: ${WOODPECKER_DB_NAME}
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2048M"
        reservations:
          cpus: "0.25"
          memory: "512M"
    networks:
      homelab-net:
        aliases:
          - database
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  homelab-net:
    external: true