# Woodpecker CI/CD Pod (woodpecker-server) Docker Compose File
# Includes woodpecker-server, woodpecker-agent
services:
  woodpecker-server:
    image: docker.io/woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    restart: unless-stopped
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE=postgres://woodpecker:${WOODPECKER_DB_PASSWORD}@database:5432/woodpecker?sslmode=disable
      - WOODPECKER_OPEN=true
      - WOODPECKER_ORGS=${GITEA_ORG}
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=gitea
      - WOODPECKER_GITEA_CLIENT=${GITEA_CLIENT_ID}
      - WOODPECKER_GITEA_SECRET=${GITEA_CLIENT_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_BACKEND_DOCKER_NETWORK=homelab-net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2048M"
        reservations:
          cpus: "0.25"
          memory: "512M"
    networks:
      homelab-net:
        aliases:
          - database
    ports:
      - 8086:8000

  woodpecker-agent-1:
    image: docker.io/woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent-1
    restart: unless-stopped
    command: agent
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_MAX_WORKFLOWS=4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1024M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    networks:
      homelab-net:
        aliases:
          - database
    depends_on:
      - woodpecker-server

volumes:
  woodpecker-server-data:
    external: true

networks:
  homelab-net:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.10.0/24"