services:
  valkey:
    image: docker.io/valkey/valkey     # Is there an Alpine image?
    container_name: valkey
    ports:
      - "6379:6379"                    # Don't expose to the net
    volumes:
      - valkey-data:/data/
    environment:
      #- VALKEY_EXTRA_FLAGS='--save 600 1 --loglevel warning'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"                  # Maximum 50% of a single CPU core
          memory: "256M"               # Maximum of 256MB of RAM
        reservations:
          cpus: "0.25"                 # Reserve 25% of a single CPU core
          memory: "128M"               # Reserve 128MB of RAM

volumes:
  valkey-data:
    external: true
